### ISSUE TITLE
cred is undefined

### ISSUE THREAD

**Issue by vanderleisp** [arjunsk/Ionic-IOT-Monitor#1]
while trying to run it in a browser, either Firefox or Chrome, I'm getting the message:
Error: cred is undefined

as seems the login is similar to the ionic-firebase-shopping-card app, and there it's working, then I'm trying to understand whats wrong here.
is there a need to setup an account at Cloud MQTT ?

**Comment by autoincr** [comment]
Yes, you need to create an account in cloudMQTT. Please refer the video and the article.

**Comment by vanderleisp** [comment]
checking video but still I couldn't signup, and getting the below message, so any idea ??
can't go to the signup page and enter the data, and then register the user at firebase, as got stuck at  http://localhost:8100/#/page1/page6

Error: cred is undefined
$scope.signupEmail@http://localhost:8100/js/controllers.js:81:9
anonymous/fn@http://localhost:8100/lib/ionic/js/ionic.bundle.js line 26457 > Function:2:373
@http://localhost:8100/lib/ionic/js/ionic.bundle.js:62386:9
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:8100/lib/ionic/js/ionic.bundle.js:29158:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:8100/lib/ionic/js/ionic.bundle.js:29257:18
@http://localhost:8100/lib/ionic/js/ionic.bundle.js:62385:7
createEventHandler/eventHandler@http://localhost:8100/lib/ionic/js/ionic.bundle.js:16583:9
triggerMouseEvent@http://localhost:8100/lib/ionic/js/ionic.bundle.js:2948:3
tapClick@http://localhost:8100/lib/ionic/js/ionic.bundle.js:2937:3
tapMouseUp@http://localhost:8100/lib/ionic/js/ionic.bundle.js:3013:5
EventListener.handleEvent*tapEventListener@http://localhost:8100/lib/ionic/js/ionic.bundle.js:2921:5
ionic.tap.register@http://localhost:8100/lib/ionic/js/ionic.bundle.js:2734:5
FrameRequestCallback*ionic.DomUtil.requestAnimationFrame@http://localhost:8100/lib/ionic/js/ionic.bundle.js:185:14
domReady@http://localhost:8100/lib/ionic/js/ionic.bundle.js:141:7
EventListener.handleEvent*@http://localhost:8100/lib/ionic/js/ionic.bundle.js:147:5
@http://localhost:8100/lib/ionic/js/ionic.bundle.js:133:2
@http://localhost:8100/lib/ionic/js/ionic.bundle.js:22:2
  ionic.bundle.js:25642:18

**Comment by autoincr** [comment]
1. Have you enabled Signing user using email/password in firebase. 
2. Have you updated firebase url in service.js
3. Have you added firebase api key to index.html
4. Did you modify the code, cause there is no mention of firebase in the error logs.So may be, this could also be a null pointer exception.

I have checked the app. It is working on my end.

**Comment by vanderleisp** [comment]
1. yes
2. .factory('fireBaseData', function($firebase) {
  var ref = new Firebase("https://iot1-xxxxx.firebaseio.com/"),
  refMqtt = new Firebase("https://iot1-xxxxx.firebaseio.com/mqtt");
  return {
    ref: function() {
      return ref;
    },
    refMqtt: function() {
      return refMqtt;
    }
  }
})

3. only difference is that the firebase.js link is different from the one you used, as this ones goes to 3.6.8 like below:

  <script src="https://cdn.firebase.com/js/client/2.2.4/firebase.js"></script>
  <script src="https://cdn.firebase.com/libs/angularfire/1.2.0/angularfire.min.js"></script>

  
	<script src="https://www.gstatic.com/firebasejs/3.6.8/firebase.js"></script>
	<script>
	  // Initialize Firebase
	  var config = {
		apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxx-xkjVfE",
		authDomain: "iot1-xxxxx.firebaseapp.com",
		databaseURL: "https://iot1-xxxxx.firebaseio.com",
		storageBucket: "iot1-xxxxx.appspot.com",
		messagingSenderId: "xxxxxxxxxxxx"
	  };
	  firebase.initializeApp(config);
	</script>

4. no, no changes in the code other than the firebase js link address on index.html, as above, as firebase direct me to this other one.

One thing I noted was that there isn't any folder/sub-folder inside the firebase iot1 that I created, so maybe the app is trying to go to the  https://iot1-xxxxx.firebaseio.com/mqtt folder, that doesn't exist yet there.
As you wrote that the Firebase DB content would have Manual entry, and there isn't yet there anything, then maybe the app is trying to save the users inside this folder /mqtt.

As the other app, ionic-firebase-shopping-card, has a similar signup and its working then maybe its this /mqtt folder the problem.

**Comment by autoincr** [comment]
Can you check once again without updating the firebase.js
Currently I don't have any clue on this issue. 
Please update me when the issue is resolved.

**Comment by vanderleisp** [comment]
![screen1](https://cloud.githubusercontent.com/assets/4840410/22629774/cc6fdcee-ebd3-11e6-8a49-847dbaad6a0a.jpg)
![screen2](https://cloud.githubusercontent.com/assets/4840410/22629777/cc76ed22-ebd3-11e6-938c-b3a4784a69d1.jpg)
![screen3](https://cloud.githubusercontent.com/assets/4840410/22629775/cc74f08a-ebd3-11e6-9746-c786f54641e1.jpg)
![screen4](https://cloud.githubusercontent.com/assets/4840410/22629776/cc764a8e-ebd3-11e6-907f-9040813996f5.jpg)

attached files shows the screen for both the IOT and the shopping cart app, as reference.
you can see that in the IOT app there is a missing md-label.scss file while trying to signup at firebase, and app screen doesn't show the name, phone, email and password fields and still shows that are in the /page1/page6 like the shopping cart app is while doing the signup.

I'll test later this change on firebase.js link, and see if this is the problem.

**Comment by vanderleisp** [comment]
case closed........ it was my mistake !!
in the shopping cart app when you click on SignUp then it shows also Name and Phone plus email and password, so I was filling these fields and clicking "Sign up with your email".
But in the IoT app when you click in SignUp there isn't any new field, so I thought that had to click on "Sign up with your email" first and then the other fields would appear... and this was the problem as clicking on this was already sending the empty fields to Firebase, and getting the "cred is undefined" message, because these wasn't data in the fields, so firebase couldn't authenticate the user.

sorry for that....

**Comment by autoincr** [comment]
Well, glad to hear that issue is solved !
