### ISSUE TITLE
IONIC 2 and Angular 2 have been released

### ISSUE THREAD

**Issue by devorrah** [arjunsk/Ionic-IOT-Monitor#2]
Hi, thank you for this project. I followed the steps carefully but when I try to see the graph page I get a configuration error: **"Check if the port is for websocket!"**

Which it is. I even tried all the ports listed. Do you know what could be wrong? 

![websocket-error](https://cloud.githubusercontent.com/assets/25807788/23005337/f0737396-f3c9-11e6-8a27-887e09e9a7c8.png)

But more importantly - will you be upgrading this project to IONIC 2 with Angular 2?

thanks,

Dev

**Comment by arjunsk** [comment]
Sorry Dev, I am yet to learn Ionic 2. I think, I also got this error, but don't remember how i solved it. Please refer stackoverflow.

**Comment by bruno-wladimir** [comment]
Has a solution ?I have the same problem.

**Comment by Pratibha4lion** [comment]
hi dev
I found this solution:
Link MQTT Server:  https://customer.cloudmqtt.com
Goto :Cloud MQTT server login with your credential and click the instance 
look like:
click Restart .
 problem shortout :)


( or you can create new instance and pass credential in your app setting page )

go to snap shot
![mqtt_snapshot](https://user-images.githubusercontent.com/33420530/33314389-7a0b2f30-d453-11e7-8f64-9005d92d9249.png)




Thank you arjun sir you great , awesome post unbeatable :)

**Comment by devorrah** [comment]
Thank you, I will give it a try.
